import crypto from "node:crypto";

function secret(){const value=process.env.SUPABASE_SECRET_KEY||process.env.DASHBOARD_PASSWORD;if(!value)throw new Error("Contact handoff secret missing");return crypto.createHash("sha256").update(`windowsprotect-contact\0${value}`).digest();}
function seal(purpose,payload){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv("aes-256-gcm",secret(),iv);cipher.setAAD(Buffer.from(purpose));const encrypted=Buffer.concat([cipher.update(JSON.stringify(payload),"utf8"),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString("base64url");}
function open(purpose,token){if(typeof token!=="string"||token.length<40||token.length>1200||!/^[A-Za-z0-9_-]+$/.test(token))throw new Error("Invalid contact handoff");const bytes=Buffer.from(token,"base64url");if(bytes.length<29)throw new Error("Invalid contact handoff");const decipher=crypto.createDecipheriv("aes-256-gcm",secret(),bytes.subarray(0,12));decipher.setAAD(Buffer.from(purpose));decipher.setAuthTag(bytes.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()]).toString("utf8"));}
export function normalizeEmail(value){const email=String(value||"").trim().toLowerCase().slice(0,254);return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)?email:"";}
export function normalizePhone(value){const input=String(value||"").trim().replace(/\s+/g," ").slice(0,40);if(!/^\+?[0-9 ().-]+$/.test(input))return"";const digits=input.replace(/\D/g,"");return digits.length>=7&&digits.length<=15?(input.startsWith("+")?"+":"")+digits:"";}
export function contactSetupLabel(fingerprint,email,phone){const cleanEmail=normalizeEmail(email),cleanPhone=normalizePhone(phone);if(!/^[a-f0-9]{24}$/.test(fingerprint||"")||!cleanEmail||!cleanPhone)throw new Error("Invalid contact details");return `public:${fingerprint}:c1:${seal("WindowsProtect setup contact v1",{email:cleanEmail,phone:cleanPhone})}`;}
export function contactFromSetupLabel(label){const match=/^public:([a-f0-9]{24}):c1:([A-Za-z0-9_-]+)$/.exec(String(label||""));if(!match)return null;const value=open("WindowsProtect setup contact v1",match[2]),email=normalizeEmail(value.email),phone=normalizePhone(value.phone);if(!email||!phone)throw new Error("Invalid contact details");return{email,phone};}
export function createEnrollmentGrant(contact,minutes=10){return seal("WindowsProtect enrollment contact v1",{email:normalizeEmail(contact.email),phone:normalizePhone(contact.phone),expires_at:new Date(Date.now()+minutes*60000).toISOString()});}
export function readEnrollmentGrant(token){const value=open("WindowsProtect enrollment contact v1",token),email=normalizeEmail(value.email),phone=normalizePhone(value.phone);if(!email||!phone||!Number.isFinite(Date.parse(value.expires_at))||Date.parse(value.expires_at)<=Date.now())throw new Error("Invalid enrollment grant");return{email,phone};}
