import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {GET} from '../app/api/agent/update/route.js';import {agentUrl,newer} from '../app/lib/agent-release.js';
process.env.SUPABASE_URL='https://db.test';process.env.SUPABASE_SECRET_KEY='server-secret';
const token='device-token',hash=crypto.createHash('sha256').update(token).digest('hex');
async function mocked(mock,fn){const original=global.fetch;global.fetch=mock;try{await fn();}finally{global.fetch=original;}}
test('semantic agent version comparison never downgrades or reinstalls equal version',()=>{assert.equal(newer('0.5.17','0.5.18'),true);assert.equal(newer('0.5.18','0.5.18'),false);assert.equal(newer('0.6.0','0.5.18'),false);});
test('agent update requires a valid enrolled device before release lookup',async()=>{await mocked(async url=>{assert.match(String(url),new RegExp(hash));return Response.json([]);},async()=>{const response=await GET(new Request('https://dashboard.test/api/agent/update?version=0.5.10',{headers:{'x-device-token':token}}));assert.equal(response.status,401);});});
test('older enrolled agent receives fixed HTTPS asset and verified manifest hash',async()=>{let calls=0;await mocked(async url=>{calls++;if(String(url).startsWith('https://db.test/'))return Response.json([{id:'device'}]);assert.match(String(url),/agent-sha256\.json$/);return Response.json({version:'0.5.18',sha256:'a'.repeat(64)});},async()=>{const response=await GET(new Request('https://dashboard.test/api/agent/update?version=0.5.17',{headers:{'x-device-token':token}}));assert.equal(response.status,200);const body=await response.json();assert.equal(body.url,agentUrl);assert.equal(body.update,true);assert.equal(body.sha256,'a'.repeat(64));assert.equal(calls,2);});});
test('current agent does not fetch a release manifest',async()=>{let calls=0;await mocked(async url=>{calls++;assert.match(String(url),/^https:\/\/db\.test/);return Response.json([{id:'device'}]);},async()=>{const response=await GET(new Request('https://dashboard.test/api/agent/update?version=0.5.18',{headers:{'x-device-token':token}}));assert.equal((await response.json()).update,false);assert.equal(calls,1);});});
