import test from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {POST as control,ultraViewerServiceCommand} from '../app/api/admin/device/[id]/ultraviewer/route.js';import {POST as heartbeat} from '../app/api/heartbeat/route.js';
process.env.SUPABASE_URL='https://db.test';process.env.SUPABASE_SECRET_KEY='server-secret';process.env.DASHBOARD_USER='test';process.env.DASHBOARD_PASSWORD='secret';
const auth='Basic '+Buffer.from('test:secret').toString('base64'),id='11111111-1111-4111-8111-111111111111';
async function mocked(mock,fn){const original=global.fetch;global.fetch=mock;try{await fn();}finally{global.fetch=original;}}
test('UltraViewer allowance changes the live Windows service configuration',()=>{const until='2026-10-01T16:00:00.000Z',allow=ultraViewerServiceCommand(true,until),block=ultraViewerServiceCommand(false,null);assert.match(allow,/UltraViewerAllowedUntilUtc/);assert.match(allow,/sc\.exe config \$t\.Name start= auto/);assert.match(allow,/sc\.exe start \$t\.Name/);assert.match(block,/sc\.exe config \$t\.Name start= disabled/);assert.throws(()=>ultraViewerServiceCommand(true,'bad'));});
test('dashboard queues a bounded UltraViewer allowance for an online pending or protected 0.5.11 PC',async()=>{const calls=[];await mocked(async(url,options={})=>{calls.push({url:String(url),options});if(String(url).includes('select=id,agent_version'))return Response.json([{id,agent_version:'0.5.11',last_seen_at:new Date().toISOString(),protection_status:'pending'}]);if(String(url).endsWith('/security_events'))return new Response(null,{status:201});return Response.json([{id}]);},async()=>{const request=new Request(`https://dashboard.test/api/admin/device/${id}/ultraviewer`,{method:'POST',headers:{authorization:auth,origin:'https://dashboard.test','content-type':'application/json'},body:JSON.stringify({action:'allow',minutes:999})});const response=await control(request,{params:Promise.resolve({id})});assert.equal(response.status,200);const patch=JSON.parse(calls.find(call=>call.options.method==='PATCH').options.body);assert.equal(patch.temporary_support_enabled,true);const minutes=(Date.parse(patch.temporary_support_expires_at)-Date.now())/60000;assert.ok(minutes>119&&minutes<=121);});});
test('older agent cannot create a misleading allowance state',async()=>{let calls=0;await mocked(async()=>{calls++;return Response.json([{id,agent_version:'0.5.10',last_seen_at:new Date().toISOString(),protection_status:'protected'}]);},async()=>{const request=new Request(`https://dashboard.test/api/admin/device/${id}/ultraviewer`,{method:'POST',headers:{authorization:auth,origin:'https://dashboard.test','content-type':'application/json'},body:JSON.stringify({action:'allow'})});const response=await control(request,{params:Promise.resolve({id})});assert.equal(response.status,409);assert.equal(calls,1);});});
test('heartbeat delivers the server allowance and ignores an old agent attempt to clear it',async()=>{const token='token',until=new Date(Date.now()+25*60000).toISOString();let saved;await mocked(async(url,options={})=>{if(!options.method)return Response.json([{id,migration_status:'completed',temporary_support_enabled:true,temporary_support_expires_at:until}]);saved=JSON.parse(options.body);return Response.json([{id}]);},async()=>{const request=new Request('https://dashboard.test/api/heartbeat',{method:'POST',headers:{'x-device-token':token,'content-type':'application/json'},body:JSON.stringify({temporary_support_enabled:false,temporary_support_expires_at:null,agent_version:'0.5.10'})});const response=await heartbeat(request);assert.equal(response.status,200);assert.equal((await response.json()).ultraviewer_allowed_until,until);assert.equal('temporary_support_enabled' in saved,false);assert.equal('temporary_support_expires_at' in saved,false);assert.ok(crypto.createHash('sha256').update(token).digest('hex'));});});
